apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prom-kube-prometheus-stack-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    
    receivers:
      - name: "null"
      - name: "node-heal-webhook"
        webhook_configs:
          - url: "http://node-heal-webhook.monitoring.svc:8000/webhook"
            send_resolved: false
    
    route:
      group_by: [namespace]
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: "null"
      routes:
        - matchers:
            - heal = "true"
          receiver: "node-heal-webhook"
          group_wait: 5s
          repeat_interval: 5m
